# Explore and Implementation of Multi-Layer Perceptron using Pytorch 

In [1]:
# We're just getting started by importing the numpy library,
# which is like a Swiss Army knife for numerical operations in Python.
# We'll be using it a lot for our matrix operations.

import numpy as np

In [3]:
# 3x2 Weight matrix for this layer,
# 2 input features, 3 output features (which means 3 perceptrons/units)
WeightMatrix = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# 2x1, 2 are the input features and 1 in the size of the batch
Input_1 = np.array([
    [0.15],
    [0.25]
])

WeightMatrix, Input_1

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[0.15],
        [0.25]]))

In [5]:
# Matrix multiplication to perform the weighted sum of the input values
# for each neuron in that layer
np.matmul(WeightMatrix, Input_1)

array([[0.65],
       [1.45],
       [2.25]])

In [7]:
# 2x3, 2 are the input features and 3 in the size of the batch
Input_1 = np.array([
    [0.15, 0.3, 0.5],
    [0.25, 0.4, 0.6]
])
np.matmul(WeightMatrix, Input_1)

array([[0.65, 1.1 , 1.7 ],
       [1.45, 2.5 , 3.9 ],
       [2.25, 3.9 , 6.1 ]])

In [9]:
# 3x2, 3 is batch size, 2 number of features
Input_2 = np.array([
    [0.15, 0.25],
    [0.3, 0.4],
    [0.5, 0.6]
])

Input_2.shape

(3, 2)

In [11]:
# This will fail as the row by columns multiplication
# requires the second dimention of the first matrix
# to be equal to the first dimension of the second.
#np.matmul(WeightMatrix, Input_2)

In [13]:
WeightMatrix.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
np.matmul(Input_2, WeightMatrix.T)

array([[0.65, 1.45, 2.25],
       [1.1 , 2.5 , 3.9 ],
       [1.7 , 3.9 , 6.1 ]])

In [17]:
bias = np.array([1.1, -2.1, -3.1])

In [19]:
np.matmul(Input_2, WeightMatrix.T) + bias

array([[ 1.75, -0.65, -0.85],
       [ 2.2 ,  0.4 ,  0.8 ],
       [ 2.8 ,  1.8 ,  3.  ]])

In [21]:
def relu(x):
    return np.maximum(0, x)

x = np.matmul(Input_2, WeightMatrix.T) + bias

relu(x)

array([[1.75, 0.  , 0.  ],
       [2.2 , 0.4 , 0.8 ],
       [2.8 , 1.8 , 3.  ]])

In [23]:
import torch
from torch import nn

In [25]:
layer = nn.Linear(2,3)

In [27]:
layer.bias

Parameter containing:
tensor([-0.3663,  0.0860,  0.3400], requires_grad=True)

In [29]:
layer.weight.data = torch.tensor([
    [1., 2.],
    [3., 4.],
    [5., 6.]
])

layer.weight

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [31]:
layer.bias.data = torch.tensor([1.1, -2.1, -3.1])


In [33]:
Input = torch.tensor([
    [0.15, 0.25],
    [0.3, 0.4],
    [0.5, 0.6]
])

Input

tensor([[0.1500, 0.2500],
        [0.3000, 0.4000],
        [0.5000, 0.6000]])

In [35]:
layer(Input)

tensor([[ 1.7500, -0.6500, -0.8500],
        [ 2.2000,  0.4000,  0.8000],
        [ 2.8000,  1.8000,  3.0000]], grad_fn=<AddmmBackward0>)

In [37]:
import torch.nn.functional as F

x= layer(Input)
F.relu(x)

tensor([[1.7500, 0.0000, 0.0000],
        [2.2000, 0.4000, 0.8000],
        [2.8000, 1.8000, 3.0000]], grad_fn=<ReluBackward0>)